# Ansible variables
ANSIBLE_SERVICE_USERNAME: 'ansi'
ANSIBLE_SERVICE_UID: '3333'

# Timezone
DEFAULT_TIMEZONE: "America/Los_Angeles"

# Network definitions
gateway: '192.168.4.1'
subnet_mask: '255.255.252.0'
subnet_CIDR: '/22'

# XDG Directory Specifications
XDG_CONFIG_HOME: "~/.config"
XDG_STATE_HOME: "~/.local/state"


# Personal home directory specifications
USER_MEDIA_ROOT: "~/media"

