---
container_name: "it-tools"
container_image_loc: "docker.io/corentinth/it-tools"
container_version_tag: "latest"
publish_ports:
  - ext: 8282
    int: 80
    proto: 'tcp'

container_image: "{{ container_image_loc }}:{{ container_version_tag }}"
quadlet_filename: "{{ container_name }}.container"
